### ISSUE TITLE
edge-js incompatible with Node 20.9.0 LTS

### ISSUE THREAD

**Issue by m4rtelli** [agracio/edge-js-quick-start#15]
'Error: The edge module has not been pre-compiled for node.js version v20.9.0. You must build a custom version of edge.node.'

Any plans to natively support Node v20 in the near future? Thanks

**Comment by agracio** [comment]
updated

**Comment by agracio** [comment]
Node v.20.x support added but troubleshooting issues with `edge-js-quick-start`

**Comment by agracio** [comment]
Updated and works with Node 20.x

**Comment by m4rtelli** [comment]
Thank you for such a quick fix. I confirmed that my node 20 project works now with the latest version of edge.
